# Generated by Django 4.0.2 on 2022-02-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('tasks', models.JSONField(blank=True)),
            ],
        ),
    ]
