# Generated by Django 4.0.2 on 2022-02-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('tasks', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItems',
        ),
    ]
