# Generated by Django 4.0.2 on 2022-02-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_tasks_delete_todoitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='tasks',
            field=models.JSONField(blank=True),
        ),
    ]
