# Generated by Django 4.0.2 on 2022-02-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_tasks_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
