# Generated by Django 4.0.2 on 2022-02-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_tasks_id_alter_tasks_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='id',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='username',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
